# =========================================
# CladeWelcome Configuration
# Version: 0.2.0.0.a
# Author: Vunlior
# =========================================

language: en

messages:
  default:
    - "cladewelcome.default"

  admin:
    - "cladewelcome.admin"

  op:
    - "cladewelcome.op"

sounds:
  enabled: true
